export const nameBand = 'JOHANN SEBASTIAN BACH';
export const nameSongs = [
	"GOLDBERG VARIATIONS, VARIATION 8", /*1*/
	"AIR ON THE G STRING", /*2*/
	"CELLO SUITE NO.1 I-PRELUDE", /*3*/
	"AIR SUITE NR. 3", /*4*/
	"GOLDBERG VARIATIONS, VARIATION 2", /*5*/
	"JAUCHZET FROHLOCKET", /*6*/
	"MATTHÄUS PASSION", /*7*/
	"SONATA II BWV 1003", /*8*/
	"ORCHESTRAL SUITE NO. 3 D-DU", /*9*/
	"GOLDBERG VARIATIONS, VARIATION 1", /*10*/
	"LITTLE FUGUE", /*11*/
	"SONATA FOR VIOLA DA GAMBA AND CLAVIER", /*12*/
	"BWV 1007 PRELUDE IN D", /*13*/
	"JESUS, ALEGRIA DOS HOMENS", /*14*/
	"GOLDBERG VARIATIONS, ARIA", /*15*/
	"SONATA FOR VIOLA DA GAMBA AND HARPSICHORD", /*16*/
	"VIOLIN SONATA NO. 1 IN G MINOR", /*17*/
	"DOUBLE VIOLIN CONCERTO IN D MINOR", /*18*/
	"FUGA IN SOL MINORE BWV 1000", /*19*/
	"AIR ON THE G STRING", /*20*/
]